---
version: 2
plugins:
  duplication:
    config:
      languages:
        - php
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  structure:
    enabled: false
exclude_patterns:
  - vendor/
  - .idea/
  - tests/
